# Generated by Django 5.1.1 on 2024-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_link', models.URLField()),
                ('cover_image', models.ImageField(upload_to='cover/')),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
